<?php

/**
 * @file
 * Primary module hooks for siddybot module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

 /**
 * Implements hook_theme().
 */
 
 function siddybot_theme($existing, $type, $theme, $path) {
 
     /*
         return [
             'forum_display' => [
                 'variables' => ['forums' => NULL, 'topics' => NULL, 'parents' => NULL, 'tid' => NULL, 'sortby' => NULL, 'forum_per_page' => NULL],
             ],
             'forum_list' => [
                 'variables' => ['forums' => NULL, 'parents' => NULL, 'tid' => NULL],
             ],
             'forum_icon' => [
                 'variables' => ['new_posts' => NULL, 'num_posts' => 0, 'comment_mode' => 0, 'sticky' => 0],
             ],
             'status_report' => [
                 'render element' => 'requirements',
                 'file' => 'system.admin.inc',
             ],
         ];
     */

     return [
         'siddybot_template' => [
            'variables' => [
                'botname' => ''
            ]
         ],
     ];
 }